<?php

/**
 * @file
 * Primary module hooks for prueba module.
 */

/**
 * Implements hook_theme().
 */
function prueba_theme(): array {
  return [
    'nueva_plantilla' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for nueva-plantilla.html.twig template.
 *
 * Default template: nueva-plantilla.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_nueva_plantilla(array &$variables): void {
  $variables['foo'] = 'bar';
}
